#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

# TODO: install emacs
# install_emacs() { }

arrange_files() {
	ln -s -f ~/workspace/repos/emacs/early-init.el ~/.emacs.d/early-init.el
	ln -s -f ~/workspace/repos/emacs/init.el ~/.emacs.d/init.el
	ln -s -f ~/workspace/repos/emacs/lisp ~/.emacs.d/lisp
}

# install_emacs
arrange_files
