#!/usr/bin/env bash

# Copy from: https://github.com/ThePrimeagen/.dotfiles/blob/master/bin/.local/scripts/tmux-sessionizer
#
search_dirs=(
    "$HOME/workspace"
    "$HOME/workspace/repos"
    "$HOME/workspace/second-brain/para/resources/programming"
)

if [[ $# -eq 1 ]]; then
    selected_fullpath=$1
else
    selected_fullpath=$(find "${search_dirs[@]}" -mindepth 1 -maxdepth 1 -type d | fzf)
fi

selected=$(echo "$selected_fullpath" | sed 's|.*/\([^/]*\)$|\1|')

mkdir -p $HOME/.local/logs/
echo "selected_fullpath=$selected_fullpath. selected=$selected." >$HOME/.local/logs/tmux.log

if [[ -z $selected ]]; then
    exit 0
fi

tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    echo "Detected no running tmux. Creating a new session with name $selected at path $selected_fullpath." >>$HOME/.local/logs/tmux.log
    tmux new-session -s $selected -c $selected_fullpath
    exit 0
fi
echo "Detected tmux running." >>$HOME/.local/logs/tmux.log

if ! tmux has-session -t=$selected 2>/dev/null; then
    echo "Creating a new session with name $selected at path $selected_fullpath." >>$HOME/.local/logs/tmux.log
    tmux new-session -ds $selected -c $selected_fullpath
fi

echo "Switch to an existing session with name $selected." >>$HOME/.local/logs/tmux.log
if [[ -z $TMUX ]]; then
    tmux attach -t $selected
else
    tmux switch-client -t $selected
fi
